homepage: "https://github.com/Q5EbA7Vdyw84efER/nextjs-dashboard"
main_repo: 'https://github.com/Q5EbA7Vdyw84efER/nextjs-dashboard.git'
language: javascript
primary_contact: "nkawxs@gmail.com"
sanitizers:
  - none